// GENERATED CODE - DO NOT MODIFY BY HAND
// This code was generated by ObjectBox. To update it run the generator again:
// With a Flutter package, run `flutter pub run build_runner build`.
// With a Dart package, run `dart run build_runner build`.
// See also https://docs.objectbox.io/getting-started#generate-objectbox-code

// ignore_for_file: camel_case_types
// coverage:ignore-file

import 'dart:typed_data';

import 'package:flat_buffers/flat_buffers.dart' as fb;
import 'package:objectbox/internal.dart'; // generated code can access "internal" functionality
import 'package:objectbox/objectbox.dart';
import 'package:objectbox_flutter_libs/objectbox_flutter_libs.dart';

import 'ObjextBox/object.user.entity.dart';

export 'package:objectbox/objectbox.dart'; // so that callers only have to import this file

final _entities = <ModelEntity>[
  ModelEntity(
      id: const IdUid(1, 2522117341636349425),
      name: 'ObjectBoxUser',
      lastPropertyId: const IdUid(7, 1571550371854984849),
      flags: 0,
      properties: <ModelProperty>[
        ModelProperty(
            id: const IdUid(1, 536244040443086042),
            name: 'id',
            type: 6,
            flags: 1),
        ModelProperty(
            id: const IdUid(2, 8016144741500915640),
            name: 'fName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(3, 1919579311574430672),
            name: 'lName',
            type: 9,
            flags: 0),
        ModelProperty(
            id: const IdUid(4, 5466757043895357396),
            name: 'birthMonth',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(5, 98543170472913625),
            name: 'birthDay',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(6, 11449171185759597),
            name: 'birthYear',
            type: 6,
            flags: 0),
        ModelProperty(
            id: const IdUid(7, 1571550371854984849),
            name: 'addedAt',
            type: 9,
            flags: 0)
      ],
      relations: <ModelRelation>[],
      backlinks: <ModelBacklink>[])
];

/// Open an ObjectBox store with the model declared in this file.
Future<Store> openStore(
        {String? directory,
        int? maxDBSizeInKB,
        int? fileMode,
        int? maxReaders,
        bool queriesCaseSensitiveDefault = true,
        String? macosApplicationGroup}) async =>
    Store(getObjectBoxModel(),
        directory: directory ?? (await defaultStoreDirectory()).path,
        maxDBSizeInKB: maxDBSizeInKB,
        fileMode: fileMode,
        maxReaders: maxReaders,
        queriesCaseSensitiveDefault: queriesCaseSensitiveDefault,
        macosApplicationGroup: macosApplicationGroup);

/// ObjectBox model definition, pass it to [Store] - Store(getObjectBoxModel())
ModelDefinition getObjectBoxModel() {
  final model = ModelInfo(
      entities: _entities,
      lastEntityId: const IdUid(1, 2522117341636349425),
      lastIndexId: const IdUid(0, 0),
      lastRelationId: const IdUid(0, 0),
      lastSequenceId: const IdUid(0, 0),
      retiredEntityUids: const [],
      retiredIndexUids: const [],
      retiredPropertyUids: const [],
      retiredRelationUids: const [],
      modelVersion: 5,
      modelVersionParserMinimum: 5,
      version: 1);

  final bindings = <Type, EntityDefinition>{
    ObjectBoxUser: EntityDefinition<ObjectBoxUser>(
        model: _entities[0],
        toOneRelations: (ObjectBoxUser object) => [],
        toManyRelations: (ObjectBoxUser object) => {},
        getId: (ObjectBoxUser object) => object.id,
        setId: (ObjectBoxUser object, int id) {
          object.id = id;
        },
        objectToFB: (ObjectBoxUser object, fb.Builder fbb) {
          final fNameOffset = fbb.writeString(object.fName);
          final lNameOffset = fbb.writeString(object.lName);
          final addedAtOffset = fbb.writeString(object.addedAt);
          fbb.startTable(8);
          fbb.addInt64(0, object.id);
          fbb.addOffset(1, fNameOffset);
          fbb.addOffset(2, lNameOffset);
          fbb.addInt64(3, object.birthMonth);
          fbb.addInt64(4, object.birthDay);
          fbb.addInt64(5, object.birthYear);
          fbb.addOffset(6, addedAtOffset);
          fbb.finish(fbb.endTable());
          return object.id;
        },
        objectFromFB: (Store store, ByteData fbData) {
          final buffer = fb.BufferContext(fbData);
          final rootOffset = buffer.derefObject(0);

          final object = ObjectBoxUser(
              id: const fb.Int64Reader().vTableGet(buffer, rootOffset, 4, 0),
              fName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 6, ''),
              lName: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 8, ''),
              addedAt: const fb.StringReader(asciiOptimization: true)
                  .vTableGet(buffer, rootOffset, 16, ''),
              birthDay:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 12, 0),
              birthMonth:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 10, 0),
              birthYear:
                  const fb.Int64Reader().vTableGet(buffer, rootOffset, 14, 0));

          return object;
        })
  };

  return ModelDefinition(model, bindings);
}

/// [ObjectBoxUser] entity fields to define ObjectBox queries.
class ObjectBoxUser_ {
  /// see [ObjectBoxUser.id]
  static final id =
      QueryIntegerProperty<ObjectBoxUser>(_entities[0].properties[0]);

  /// see [ObjectBoxUser.fName]
  static final fName =
      QueryStringProperty<ObjectBoxUser>(_entities[0].properties[1]);

  /// see [ObjectBoxUser.lName]
  static final lName =
      QueryStringProperty<ObjectBoxUser>(_entities[0].properties[2]);

  /// see [ObjectBoxUser.birthMonth]
  static final birthMonth =
      QueryIntegerProperty<ObjectBoxUser>(_entities[0].properties[3]);

  /// see [ObjectBoxUser.birthDay]
  static final birthDay =
      QueryIntegerProperty<ObjectBoxUser>(_entities[0].properties[4]);

  /// see [ObjectBoxUser.birthYear]
  static final birthYear =
      QueryIntegerProperty<ObjectBoxUser>(_entities[0].properties[5]);

  /// see [ObjectBoxUser.addedAt]
  static final addedAt =
      QueryStringProperty<ObjectBoxUser>(_entities[0].properties[6]);
}
